# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 19:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajuste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.SmallIntegerField(unique=True)),
            ],
            options={
                'ordering': ['valor'],
                'verbose_name_plural': 'ajustes',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=25, unique=True, verbose_name='descripci\xf3n')),
                ('prioridad', models.PositiveSmallIntegerField(unique=True)),
                ('color', models.CharField(max_length=6, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prioridad'],
                'verbose_name': 'categor\xeda',
                'verbose_name_plural': 'categor\xedas',
            },
        ),
        migrations.CreateModel(
            name='FactorDeAjuste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='descripci\xf3n')),
            ],
            options={
                'ordering': ['descripcion'],
                'verbose_name': 'factor de ajuste',
                'verbose_name_plural': 'factores de ajuste',
            },
        ),
        migrations.CreateModel(
            name='FactorDeCategorizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='descripci\xf3n')),
            ],
            options={
                'ordering': ['descripcion'],
                'verbose_name': 'factor de categorizaci\xf3n',
                'verbose_name_plural': 'factores de categorizaci\xf3n',
            },
        ),
        migrations.CreateModel(
            name='ReglaDeAjuste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Regla de ajuste',
                'verbose_name_plural': 'Reglas de ajuste',
            },
        ),
        migrations.CreateModel(
            name='ReglaDePreCategorizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Regla de ajuste',
                'verbose_name_plural': 'Reglas de ajuste',
            },
        ),
        migrations.CreateModel(
            name='ValorPosibleDeAjuste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='descripci\xf3n')),
                ('factorDeAjuste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.FactorDeAjuste')),
            ],
            options={
                'ordering': ['descripcion'],
                'verbose_name': 'Valor posible de factor de ajuste',
                'verbose_name_plural': 'Valores posibles de factores de ajuste',
            },
        ),
        migrations.CreateModel(
            name='ValorPosibleDeCategorizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='descripci\xf3n')),
                ('factorDeCategorizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.FactorDeCategorizacion')),
            ],
            options={
                'ordering': ['descripcion'],
                'verbose_name': 'Valor posible de factor de categorizaci\xf3n',
                'verbose_name_plural': 'Valores posibles de factores de categorizaci\xf3n',
            },
        ),
        migrations.AddField(
            model_name='regladeprecategorizacion',
            name='condicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.ValorPosibleDeCategorizacion'),
        ),
        migrations.AddField(
            model_name='regladeprecategorizacion',
            name='resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Categoria'),
        ),
        migrations.AddField(
            model_name='regladeajuste',
            name='condicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.ValorPosibleDeAjuste'),
        ),
        migrations.AddField(
            model_name='regladeajuste',
            name='resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Ajuste'),
        ),
    ]
