# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FactorDeCategorizacion',
            new_name='FactorDePreCategorizacion',
        ),
        migrations.RenameModel(
            old_name='ValorPosibleDeAjuste',
            new_name='ValorDeFactorDeAjuste',
        ),
        migrations.RenameModel(
            old_name='ValorPosibleDeCategorizacion',
            new_name='ValorDeFactorDePreCategorizacion',
        ),
        migrations.AlterModelOptions(
            name='factordeprecategorizacion',
            options={'ordering': ['descripcion'], 'verbose_name': 'factor de pre-categorizaci\xf3n', 'verbose_name_plural': 'factores de pre-categorizaci\xf3n'},
        ),
        migrations.AlterModelOptions(
            name='valordefactordeajuste',
            options={'ordering': ['descripcion'], 'verbose_name': 'Valor de factor de ajuste', 'verbose_name_plural': 'Valores de factor de ajuste'},
        ),
        migrations.AlterModelOptions(
            name='valordefactordeprecategorizacion',
            options={'ordering': ['descripcion'], 'verbose_name': 'Valor de factor de pre-categorizaci\xf3n', 'verbose_name_plural': 'Valores de factor de pre-categorizaci\xf3n'},
        ),
        migrations.RenameField(
            model_name='valordefactordeprecategorizacion',
            old_name='factorDeCategorizacion',
            new_name='factorDePreCategorizacion',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='modificado',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='modificado_por',
        ),
    ]
