# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regladeajuste',
            name='condicion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rules.ValorDeFactorDeAjuste', verbose_name='condición'),
        ),
        migrations.AlterField(
            model_name='regladeprecategorizacion',
            name='condicion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rules.ValorDeFactorDePreCategorizacion', verbose_name='condición'),
        ),
    ]
