# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_auto_20170529_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regladeprecategorizacion',
            options={'ordering': ['id'], 'verbose_name': 'Regla de pre-categorizaci\xf3n', 'verbose_name_plural': 'Reglas de pre-categorizaci\xf3n'},
        ),
    ]
