# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_auto_20170809_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factordeprecategorizacion',
            options={'ordering': ['descripcion'], 'verbose_name': 'factor de precategorización', 'verbose_name_plural': 'factores de precategorización'},
        ),
        migrations.AlterModelOptions(
            name='regladeprecategorizacion',
            options={'ordering': ['id'], 'verbose_name': 'Regla de precategorización', 'verbose_name_plural': 'Reglas de precategorización'},
        ),
        migrations.AlterModelOptions(
            name='valordefactordeprecategorizacion',
            options={'ordering': ['factorDePreCategorizacion'], 'verbose_name': 'Valor de factor de precategorización', 'verbose_name_plural': 'Valores de factor de precategorización'},
        ),
        migrations.AlterField(
            model_name='valordefactordeprecategorizacion',
            name='factorDePreCategorizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.FactorDePreCategorizacion', verbose_name='factor de precategorización'),
        ),
    ]
