# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_auto_20170529_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajuste',
            name='fue_anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoria',
            name='fue_anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factordeajuste',
            name='fue_anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factordeprecategorizacion',
            name='fue_anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regladeajuste',
            name='fue_anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regladeajuste',
            name='prioridad',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regladeprecategorizacion',
            name='fue_anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regladeprecategorizacion',
            name='prioridad',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valordefactordeajuste',
            name='fue_anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='valordefactordeprecategorizacion',
            name='fue_anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='regladeajuste',
            unique_together=set([('resultado', 'prioridad')]),
        ),
        migrations.AlterUniqueTogether(
            name='regladeprecategorizacion',
            unique_together=set([('resultado', 'prioridad')]),
        ),
    ]
