# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_auto_20170531_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='color',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='prioridad',
            field=models.PositiveSmallIntegerField(default=0, unique=True),
        ),
    ]
