# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_auto_20170605_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajuste',
            name='fue_anulado',
        ),
    ]
