# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0007_auto_20170606_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regladeajuste',
            name='prioridad',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='valordefactordeajuste',
            name='factorDeAjuste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.FactorDeAjuste', verbose_name='factor de ajuste'),
        ),
        migrations.AlterField(
            model_name='valordefactordeprecategorizacion',
            name='factorDePreCategorizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.FactorDePreCategorizacion', verbose_name='factor de pre-categorización'),
        ),
    ]
