# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 18:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0008_auto_20170607_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='prioridad',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='regladeajuste',
            name='prioridad',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='regladeprecategorizacion',
            name='prioridad',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
    ]
