# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0009_auto_20170609_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valordefactordeajuste',
            name='descripcion',
            field=models.CharField(max_length=50, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='valordefactordeprecategorizacion',
            name='descripcion',
            field=models.CharField(max_length=50, verbose_name='descripción'),
        ),
        migrations.AlterUniqueTogether(
            name='valordefactordeajuste',
            unique_together=set([('descripcion', 'factorDeAjuste')]),
        ),
        migrations.AlterUniqueTogether(
            name='valordefactordeprecategorizacion',
            unique_together=set([('descripcion', 'factorDePreCategorizacion')]),
        ),
    ]
