# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0010_auto_20170609_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valordefactordeajuste',
            options={'ordering': ['factorDeAjuste'], 'verbose_name': 'Valor de factor de ajuste', 'verbose_name_plural': 'Valores de factor de ajuste'},
        ),
        migrations.AlterModelOptions(
            name='valordefactordeprecategorizacion',
            options={'ordering': ['factorDePreCategorizacion'], 'verbose_name': 'Valor de factor de pre-categorización', 'verbose_name_plural': 'Valores de factor de pre-categorización'},
        ),
    ]
