# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 18:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0011_auto_20170609_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regladeajuste',
            name='condicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.ValorDeFactorDeAjuste', unique=True, verbose_name='condición'),
        ),
        migrations.AlterField(
            model_name='regladeajuste',
            name='prioridad',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='regladeprecategorizacion',
            name='condicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.ValorDeFactorDePreCategorizacion', unique=True, verbose_name='condición'),
        ),
        migrations.AlterField(
            model_name='regladeprecategorizacion',
            name='prioridad',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(999)]),
        ),
    ]
