# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 03:14
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('dni', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999), django.core.validators.MinValueValidator(1000000)], verbose_name='DNI')),
                ('matricula', models.PositiveIntegerField(unique=True, verbose_name='matrícula')),
                ('telefono', models.CharField(max_length=15, verbose_name='teléfono')),
                ('generador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico_generador', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dni'],
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
    ]
