# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='fcm_code',
            field=models.CharField(default='dfgdlfgndligfldfg.dfgpdlgf', help_text='Firebase Cloud Messaging Code', max_length=250, verbose_name='FCM'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medico',
            name='dni',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='DNI'),
        ),
    ]
