# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_auto_20170807_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='fcm_code',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging Code', max_length=250, verbose_name='FCM'),
        ),
    ]
