# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 15:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_auto_20170807_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'ordering': ['dni'], 'verbose_name': 'médico', 'verbose_name_plural': 'médicos'},
        ),
        migrations.AddField(
            model_name='medico',
            name='estado',
            field=models.CharField(choices=[('1', 'Disponible'), ('2', 'No disponible'), ('3', 'En auxilio')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='medico',
            name='dni',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999), django.core.validators.MinValueValidator(1000000)], verbose_name='DNI'),
        ),
    ]
