# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0004_auto_20170814_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Disponible'), (2, 'No disponible'), (3, 'En auxilio')], default=2),
        ),
    ]
