# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0005_auto_20170814_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='ubicacion_gps',
            field=models.CharField(blank=True, max_length=120, verbose_name='ubicación gps'),
        ),
    ]
