# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0006_medico_ubicacion_gps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='ubicacion_gps',
            field=models.CharField(blank=True, help_text='Coordenadas - Latitud/Longitud', max_length=120, verbose_name='ubicación gps'),
        ),
    ]
