# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 23:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0007_auto_20170823_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='latitud_gps', 
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(-180.0), django.core.validators.MinValueValidator(180.0)]),
        ),
        migrations.AddField(
            model_name='medico',
            name='longitud_gps',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(-180.0), django.core.validators.MinValueValidator(180.0)]),
        ),
    ]
