# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0009_auto_20170911_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='timestamp_gps',
            field=models.DateTimeField(blank=True, help_text='Última actualización de ubicación GPS', null=True),
        ),
    ]
