# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 20:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDeAuxilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.CharField(max_length=120, verbose_name='ubicación')),
                ('contacto_solicitante', models.CharField(max_length=120, verbose_name='contacto del solicitante')),
                ('motivo', models.TextField()),
                ('observaciones', models.CharField(max_length=120, verbose_name='descripción')),
                ('generador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Solicitudes de auxilio',
                'ordering': ['-id'],
                'verbose_name': 'Solicitud de auxilio',
            },
        ),
    ]
