# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 16:15
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('1', 'En camino'), ('2', 'En el lugar'), ('3', 'Cancelada'), ('4', 'En traslado')], default='1', max_length=1)),
                ('generador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Auxilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('1', 'Pendiente'), ('2', 'En curso'), ('3', 'Cancelado'), ('4', 'Finalizado')], default='1', max_length=1)),
                ('asignaciones', models.ManyToManyField(null=True, to='auxilios.Asignacion')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Categoria')),
            ],
            options={
                'verbose_name': 'Auxilio',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Movil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('1', 'Disponible'), ('2', 'No disponible'), ('3', 'En auxilio')], default='2', max_length=1)),
                ('patente', models.CharField(default='1', max_length=10)),
                ('generador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Móvil',
                'verbose_name_plural': 'Móviles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudDeAuxilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('sexo', models.CharField(blank=True, choices=[('F', 'F'), ('M', 'M')], max_length=1)),
                ('cantidad_pacientes', models.PositiveSmallIntegerField(default=1)),
                ('cantidad_moviles', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('ubicacion', models.CharField(max_length=120, verbose_name='ubicación')),
                ('ubicacion_especifica', models.CharField(blank=True, max_length=120, verbose_name='ubicación especifica')),
                ('ubicacion_coordenadas', models.CharField(blank=True, max_length=120, verbose_name='ubicación coordenadas')),
                ('contacto', models.CharField(blank=True, max_length=120, verbose_name='contacto')),
                ('motivo', models.TextField()),
                ('observaciones', models.CharField(blank=True, max_length=120)),
                ('generador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de auxilio',
                'verbose_name_plural': 'Solicitudes de auxilio',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='auxilio',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxilios.SolicitudDeAuxilio'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='movil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxilios.Movil'),
        ),
    ]
