# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxilio',
            name='asignaciones',
            field=models.ManyToManyField(blank=True, to='auxilios.Asignacion'),
        ),
    ]
