# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddeauxilio',
            name='observaciones',
            field=models.CharField(blank=True, max_length=120, verbose_name='descripción'),
        ),
    ]
