# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 01:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auxilios', '0002_auto_20170715_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10)),
                ('matricula', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('apelliido', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=1)),
                ('telefono', models.CharField(max_length=15)),
                ('generador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'ordering': ['id'],
            },
        ),
    ]
