# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0002_auto_20170706_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddeauxilio',
            name='contacto_solicitante',
            field=models.CharField(blank=True, max_length=120, verbose_name='contacto del solicitante'),
        ),
    ]
