# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0003_medico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'ordering': ['-id'], 'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='apelliido',
            new_name='apellido',
        ),
        migrations.AlterField(
            model_name='medico',
            name='sexo',
            field=models.CharField(max_length=2),
        ),
    ]
