# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0003_auto_20170706_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddeauxilio',
            name='observaciones',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
