# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0004_auto_20170719_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movil',
            options={'ordering': ['-id'], 'verbose_name': 'Móvil', 'verbose_name_plural': 'Móviles'},
        ),
        migrations.AlterField(
            model_name='movil',
            name='patente',
            field=models.CharField(max_length=10),
        ),
    ]
