# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0005_auto_20170725_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddeauxilio',
            name='ubicacion_coordenadas',
            field=models.CharField(max_length=120, verbose_name='ubicación coordenadas'),
        ),
    ]
