# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0005_auto_20170708_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddeauxilio',
            name='cantidad_pacientes',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
