# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 18:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0006_auto_20170708_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('1', 'En camino'), ('2', 'En el lugar'), ('3', 'Cancelada'), ('4', 'En traslado')], default='1', max_length=1)),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Auxilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('1', 'Pendiente'), ('2', 'En curso'), ('3', 'Cancelado'), ('4', 'Finalizado')], default='1', max_length=1)),
                ('asignaciones', models.ManyToManyField(to='auxilios.Asignacion')),
            ],
            options={
                'verbose_name': 'Auxilio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Movil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('1', 'Disponible'), ('2', 'No disponible'), ('3', 'En auxilio')], default='2', max_length=1)),
            ],
            options={
                'verbose_name': 'Móvil',
                'verbose_name_plural': 'Móviles',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='solicituddeauxilio',
            name='cantidad_moviles',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='auxilio',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxilios.SolicitudDeAuxilio'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='movil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxilios.Movil'),
        ),
    ]
