# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0007_auto_20170708_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='movil',
            name='patente',
            field=models.CharField(blank=True, max_length=10, verbose_name='patente'),
        ),
    ]
