# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0008_movil_patente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movil',
            name='patente',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
