# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0008_auto_20170726_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadoauxilio',
            name='generador',
        ),
        migrations.RemoveField(
            model_name='auxilio',
            name='estados',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='fcmc',
        ),
        migrations.AddField(
            model_name='auxilio',
            name='estado',
            field=models.CharField(choices=[('1', 'Pendiente'), ('2', 'En curso'), ('3', 'Cancelado'), ('4', 'Finalizado')], default='1', max_length=1),
        ),
        migrations.DeleteModel(
            name='EstadoAuxilio',
        ),
    ]
