# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 20:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auxilios', '0009_auto_20170708_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='movil',
            name='generador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movil',
            name='patente',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
