# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0011_auto_20170729_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auxilio',
            options={'ordering': ['categoria', 'prioridad', 'solicitud'], 'verbose_name': 'Auxilio'},
        ),
        migrations.AlterField(
            model_name='auxilio',
            name='prioridad',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
