# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 18:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0012_auto_20170729_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'ordering': ['dni'], 'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.RemoveField(
            model_name='medico',
            name='id',
        ),
        migrations.AddField(
            model_name='medico',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='registrado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medico',
            name='dni',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medico',
            name='matricula',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='medico',
            name='sexo',
            field=models.CharField(blank=True, choices=[('F', 'F'), ('M', 'M')], max_length=1),
        ),
        migrations.AlterField(
            model_name='solicituddeauxilio',
            name='cantidad_pacientes',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad de pacientes'),
        ),
    ]
