# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 17:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0014_auto_20170804_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='dni',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(100)], verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='teléfono'),
        ),
    ]
