# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0015_auto_20170805_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='generador',
        ),
        migrations.DeleteModel(
            name='Medico',
        ),
    ]
