# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0016_auto_20170807_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddeauxilio',
            name='cantidad_moviles',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='solicituddeauxilio',
            name='cantidad_pacientes',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='cantidad de pacientes'),
        ),
    ]
