# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 15:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0017_auto_20170808_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddeauxilio',
            name='cantidad_pacientes',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad de pacientes'),
        ),
        migrations.AlterField(
            model_name='solicituddeauxilio',
            name='ubicacion_coordenadas',
            field=models.CharField(blank=True, max_length=120, verbose_name='ubicación coordenadas'),
        ),
    ]
