# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0005_auto_20170814_1230'),
        ('auxilios', '0018_auto_20170814_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='generador',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='movil',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default='2017-08-19 0:0:0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignacion',
            name='medico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicos.Medico'),
            preserve_default=False,
        ),
    ]
