# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0019_auto_20170819_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='estado',
            field=models.CharField(choices=[('1', 'En camino'), ('2', 'En el lugar'), ('3', 'Cancelada'), ('4', 'En traslado'), ('5', 'Desviada'), ('6', 'Finalizada')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='solicituddeauxilio',
            name='cantidad_moviles',
            field=models.PositiveSmallIntegerField(default=1, help_text='Cantidad de médicos requeridos'),
        ),
    ]
