# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0021_remove_estadoauxilio_generador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'ordering': ['-id'], 'verbose_name': 'Asignación', 'verbose_name_plural': 'Asignaciones'},
        ),
    ]
