# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0022_auto_20170823_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacion',
            old_name='fecha',
            new_name='creada',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='modificada',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='estado',
            field=models.CharField(choices=[('0', 'Pendiente'), ('1', 'En camino'), ('2', 'En el lugar'), ('3', 'Cancelada'), ('4', 'En traslado'), ('5', 'Desviada'), ('6', 'Finalizada')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicos.Medico'),
        ),
    ]
