# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 19:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0023_auto_20170824_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioFinalizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia_realizada', models.BooleanField()),
                ('observaciones', models.TextField(blank=True)),
                ('motivo_inasistencia', models.CharField(blank=True, choices=[('1', 'Ubicación incorrecta'), ('2', 'No responde'), ('3', 'Ya fue trasladado'), ('4', 'Otro')], help_text='¿Por qué no pudo asistir al paciente?', max_length=1)),
                ('categorizacion', models.CharField(blank=True, choices=[('3', 'Sub-categorizado'), ('2', 'Apropiadamente categorizado'), ('1', 'Sobre-categorizado')], help_text='¿Cuál es su opinión acerca de la categorización del auxilio?', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999999), django.core.validators.MinValueValidator(1000000)], verbose_name='DNI')),
                ('apellido', models.CharField(blank=True, max_length=40)),
                ('nombre', models.CharField(blank=True, max_length=40)),
                ('fecha_naciemiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='teléfono')),
                ('motivo_atencion', models.TextField()),
                ('trasladado', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='formulariofinalizacion',
            name='datos_pacientes',
            field=models.ManyToManyField(to='auxilios.Paciente'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='formulario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auxilios.FormularioFinalizacion'),
        ),
    ]
