# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0024_auto_20170824_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='formulario',
        ),
        migrations.RemoveField(
            model_name='formulariofinalizacion',
            name='datos_pacientes',
        ),
        migrations.RemoveField(
            model_name='formulariofinalizacion',
            name='id',
        ),
        migrations.AddField(
            model_name='formulariofinalizacion',
            name='asignacion',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auxilios.Asignacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulariofinalizacion',
            name='pacientes',
            field=models.ManyToManyField(blank=True, to='auxilios.Paciente'),
        ),
        migrations.AlterField(
            model_name='formulariofinalizacion',
            name='categorizacion',
            field=models.CharField(blank=True, choices=[('3', 'Sub-categorizado'), ('2', 'Apropiadamente categorizado'), ('1', 'Sobre-categorizado')], help_text='¿Cuál es su opinión acerca de la categorización del auxilio?', max_length=1, verbose_name='categorización'),
        ),
    ]
