# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0025_auto_20170824_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddeauxilio',
            name='cantidad_moviles',
            field=models.PositiveSmallIntegerField(default=1, help_text=b'Cantidad de m\xc3\xa9dicos requeridos'),
        ),
    ]
