# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0026_auto_20170911_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='fecha_naciemiento',
            new_name='fecha_nacimiento',
        ),
        migrations.AlterField(
            model_name='solicituddeauxilio',
            name='cantidad_moviles',
            field=models.PositiveSmallIntegerField(default=1, help_text='Cantidad de médicos requeridos'),
        ),
    ]
