# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0028_auto_20170912_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxilio',
            name='codigo_suscripcion',
            field=models.CharField(default=42, max_length=10, verbose_name='código de suscripción'),
            preserve_default=False,
        ),
    ]
