# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0029_auxilio_codigo_suscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddeauxilio',
            name='origen',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Android App'), (1, 'Web App'), (2, 'WhatsApp')], default=1),
        ),
        migrations.AlterField(
            model_name='auxilio',
            name='codigo_suscripcion',
            field=models.CharField(max_length=10, unique=True, verbose_name='código de suscripción'),
        ),
    ]
