# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0030_auto_20170919_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
