# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0036_auto_20170920_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='diagnostico',
            field=models.TextField(verbose_name='diagnóstico'),
        ),
    ]
