# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 12:52
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0037_auto_20170920_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicituddeauxilio',
            name='ubicacion_coordenadas',
        ),
        migrations.AddField(
            model_name='solicituddeauxilio',
            name='latitud_gps',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(180.0), django.core.validators.MinValueValidator(-180.0)]),
        ),
        migrations.AddField(
            model_name='solicituddeauxilio',
            name='longitud_gps',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(180.0), django.core.validators.MinValueValidator(-180.0)]),
        ),
        migrations.AlterField(
            model_name='solicituddeauxilio',
            name='generador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
