# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0038_auto_20170927_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicituddeauxilio',
            options={'ordering': ['id'], 'verbose_name': 'Solicitud de auxilio', 'verbose_name_plural': 'Solicitudes de auxilio'},
        ),
        migrations.RemoveField(
            model_name='suscriptor',
            name='id',
        ),
        migrations.AlterField(
            model_name='solicituddeauxilio',
            name='contacto',
            field=models.CharField(blank=True, max_length=120, verbose_name='número de contacto'),
        ),
        migrations.AlterField(
            model_name='solicituddeauxilio',
            name='origen',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Mobile'), (1, 'Web'), (2, 'Agente virtual')], default=1),
        ),
        migrations.AlterField(
            model_name='solicituddeauxilio',
            name='sexo',
            field=models.CharField(blank=True, choices=[('F', 'Fem.'), ('M', 'Masc.')], max_length=1),
        ),
        migrations.AlterField(
            model_name='solicituddeauxilio',
            name='ubicacion_especifica',
            field=models.CharField(blank=True, max_length=120, verbose_name='referencia'),
        ),
        migrations.AlterField(
            model_name='suscriptor',
            name='codigo',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging Code', max_length=250, primary_key=True, serialize=False, verbose_name='código'),
        ),
    ]
