# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0039_auto_20171106_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscriptor',
            name='id',
            field=models.AutoField(auto_created=True, default=3, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suscriptor',
            name='codigo',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging Code', max_length=250, verbose_name='código'),
        ),
    ]
